server {
  listen 80;
  root /usr/share/nginx/html;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;
  add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https://login.microsoftonline.com; frame-src https://login.microsoftonline.com; img-src 'self' data:; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'" always;
  location /api/ { proxy_pass http://api:8000; }
  location /dev-idp/ { proxy_pass http://api:8000; }
  location / { try_files $uri /index.html; }
}
