import { useState } from "react";
import { api, type AnswerResponse, type TokenProvider } from "../api";

const ABSTAIN_TEXT: Record<string, string> = {
  insufficient_evidence: "I couldn't find enough evidence in documents you can access to answer this.",
  judge_unavailable: "The answer could not be reviewed, so it was withheld (high-assurance mode).",
  judge_abstained: "The reviewer found the draft answer unsupported, so it was withheld.",
  unsupported_after_repair: "The answer could not be supported by the evidence after revision.",
};

function freshness(iso: string | null): string {
  if (!iso) return "unknown";
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

export function Answer({
  answer,
  tokens,
  onOpenCitation,
}: {
  answer: AnswerResponse;
  tokens: TokenProvider;
  onOpenCitation: (openUrl: string) => void;
}) {
  const citationNumber = new Map(answer.citations.map((c, i) => [c.citation_id, i + 1]));

  if (answer.status === "abstained") {
    return (
      <div className="answer abstained" role="status">
        <p>
          <strong>No answer.</strong>{" "}
          {ABSTAIN_TEXT[answer.abstain_reason ?? ""] ??
            (answer.abstain_reason?.startsWith("model_unavailable")
              ? "The answer service is temporarily unavailable."
              : "No supported answer is available.")}
        </p>
        <Feedback answer={answer} tokens={tokens} />
      </div>
    );
  }

  return (
    <div className="answer">
      {answer.status === "limited" && (
        <p className="pill warn" role="note">
          Limited answer — evidence covers only part of the question.
        </p>
      )}
      <ul className="claims">
        {answer.claims.map((claim, i) => (
          <li key={i}>
            {claim.text}{" "}
            {claim.citation_ids.map((cid) => {
              const c = answer.citations.find((x) => x.citation_id === cid);
              if (!c) return null;
              return (
                <button
                  key={cid}
                  type="button"
                  className="cite"
                  aria-label={`Open source ${citationNumber.get(cid)}: ${c.title}, ${c.location}`}
                  onClick={() => onOpenCitation(c.open_url)}
                >
                  [{citationNumber.get(cid)}]
                </button>
              );
            })}
          </li>
        ))}
      </ul>
      {answer.conflicts.length > 0 && (
        <div className="conflicts" role="note">
          <strong>Sources disagree:</strong>
          <ul>
            {answer.conflicts.map((c, i) => (
              <li key={i}>{c}</li>
            ))}
          </ul>
        </div>
      )}
      {answer.outdated_sources.length > 0 && (
        <p className="pill warn" role="note">
          Outdated revision cited: {answer.outdated_sources.join(", ")}
        </p>
      )}
      <ol className="sources" aria-label="Sources">
        {answer.citations.map((c) => (
          <li key={c.citation_id}>
            <button type="button" className="link" onClick={() => onOpenCitation(c.open_url)}>
              {c.title}
            </button>{" "}
            <span className="muted">
              {c.location} · {c.section} · source updated {freshness(c.source_modified_at)} · permissions synced{" "}
              {freshness(c.acl_synced_at)}
              {!c.is_latest_revision && " · older revision"}
            </span>
          </li>
        ))}
      </ol>
      <p className="muted small">
        {answer.mode === "high_assurance" ? `Reviewed (${answer.judge_status}). ` : ""}
        {answer.from_cache ? "Served from validated cache. " : ""}
        {answer.inference_mode === "fixture" ? "Generated by deterministic FIXTURE models. " : ""}
        Trace {answer.trace_id}
      </p>
      <Feedback answer={answer} tokens={tokens} />
    </div>
  );
}

function Feedback({ answer, tokens }: { answer: AnswerResponse; tokens: TokenProvider }) {
  const [sent, setSent] = useState<"up" | "down" | null>(null);
  const [failed, setFailed] = useState(false);

  async function send(rating: "up" | "down") {
    try {
      await api.feedback(tokens, answer.run_id, rating, rating === "down" ? "other" : null, null);
      setSent(rating);
    } catch {
      setFailed(true);
    }
  }

  if (sent) return <p className="muted small">Thanks for the feedback.</p>;
  return (
    <div className="feedback" aria-label="Rate this answer">
      <button type="button" onClick={() => void send("up")} aria-label="Helpful">
        👍
      </button>
      <button type="button" onClick={() => void send("down")} aria-label="Not helpful">
        👎
      </button>
      {failed && (
        <span role="alert" className="error small">
          Feedback could not be saved.
        </span>
      )}
    </div>
  );
}
